 export const ActionTypes = {
    SET_RESERVATIONS: "SET_RESERVATIONS",
    ADD_RESERVATIONS:"ADD_RESERVATIONS",
    SELECTED_RESERVATIONS: "SELECTED_RESERVATIONS",
    SET_PENDING_COUNT: 'SET_PENDING_COUNT'
}